# code from the following sources:
# https://www.youtube.com/watch?v=Zd014DjonqE
# https://cloud.google.com/build/docs/build-config-file-schema
# https://dev.to/johannesvitt/a-cicd-pipeline-for-a-react-app-with-google-cloud-build-2cjf

steps:
# Install
- name: 'gcr.io/cloud-builders/yarn'
  args: ['add', 'package.json']

# Lint
- name: 'gcr.io/cloud-builders/yarn'
  args: ['eslint']

# TODO: Add in '--coverage' flag after coverage reaches 80%
# Test
- name: 'gcr.io/cloud-builders/yarn'
  args: ['test']

# TODO: Add in integration testing step

# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA', '.',
  '--build-arg', 'REACT_APP_ENV=$_REACT_APP_ENV'
  ]

# Push Docker Image to GCP Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']

# Deploy to Cloud Run
# REACT_APP_ENV is one of ['DEV', 'QA', 'PROD']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'pwcblog', '--image', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA',
    '--platform=managed', '--region=us-west1', '--allow-unauthenticated', '--memory', '1G'
    ]
